baseurl = "megnbenson.github.io"
title = "Meg"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

#posts
  [[params.navlinks]]
  name = "projects/"
  url = "projects/"
  
#photos
  [[params.navlinks]]
  name = "sketches/"
  url = "sketches/"
